<Project>
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableHarmony>true</EnableHarmony>
    <GamePath Condition="'$(GamePath)' == ''">/Applications/Stardew Valley.app/Contents/MacOS</GamePath>
    <EnableModDeploy>false</EnableModDeploy>
    <EnableModZip>false</EnableModZip>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)shared/FarmMenu/*.cs" Link="FarmMenu/%(Filename)%(Extension)" />
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
  </ItemGroup>
</Project>
